services:
  backend:
    build:
      context: ./  # Контекст сборки — корневая папка проекта
      dockerfile: Dockerfile  # Указываем имя Dockerfile
    env_file:
      - .env  # Подключаем переменные
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d
volumes:
  postgres_data:
