scalar DateTime

enum ProductSource {
    Manual
    Steam
}

type Price {
    currency: String!
    value: Float!
}

type Booking {
    nickname: String!
    date: String!
}

type Wish {
    id: ID!
    name: String!
    description: String
    link: String
    img: String
    rate: Int!
    type: ProductSource!
    price: Price
    creator: User!
    wishlists: [Wishlist!]!
    createdAt: DateTime!
    updatedAt: DateTime!
}

type Wishlist {
    id: ID!
    name: String!
    description: String
    creator: User!
    wishes: [Wish!]!
#    createdAt: DateTime!
#    updatedAt: DateTime!
}

type User {
    id: ID!
    telegramId: String!
    username: String!
    firstName: String!
    lastName: String
    photoUrl: String!
    wishlists: [Wishlist!]!
    wishes: [Wish!]!
}

input AuthPayload {
    id: Int!
    first_name: String!
    last_name: String
    username: String!
    photo_url: String!
    auth_date: Int!
    hash: String!
}

input PriceInput {
    currency: String!
    value: Float!
}

input WishInput {
    name: String!
    description: String
    link: String
    img: String
    rate: Int
    type: ProductSource!
    price: PriceInput
    wishlistIds: [ID!]!
}

input WishlistInput {
    name: String!
    description: String
    wishIds: [ID!]
}

type Query {
    me: User!
    user(id: ID!): User
    wish(id: ID!): Wish!
    wishes: [Wish!]!
    wishlists: [Wishlist!]!
}

type Mutation {
    login(authPayload: AuthPayload!): User
    logout: Boolean!
    createWish(wishInput: WishInput!): Wish!
    updateWish(id: ID!, wishInput: WishInput!): Wish!
    deleteWish(id: ID!): Boolean!
    createWishlist(wishlistInput: WishlistInput!): Wishlist!
    updateWishlist(id: ID!, wishlistInput: WishlistInput!): Wishlist!
}
