type User {
    id: ID!
    telegramId: String!
    username: String!
    firstName: String!
    lastName: String!
    photoUrl: String!
    wishlists: [Wishlist]
    wishes: [Wish]
}

type Wishlist {
    id: ID!
    name: String!
    creator: User!
    wishes: [Wish!]
}

type Wish {
    id: ID!
    name: String!
    url: String
    pictureUrl: String
    booking: Booking
    creator: User!
    wishlists: [Wishlist]
    orderDate: String
    price: String
}

type Booking {
    nickname: String!
    date: String!
}

input AuthPayload {
    id: Int!
    first_name: String!
    last_name: String!
    username: String!
    photo_url: String!
    auth_date: Int!
    hash: String!
}

type Query {
    users: [User!]!
    user(id: ID!): User
    wishlists: [Wishlist!]
    wishes: [Wish!]
    me: User!
}

type Mutation {
    createWishlist(name: String!): Wishlist
    createWish(name: String!): Wish
    login(
        authPayload: AuthPayload!
    ): User
    logout: Boolean!
}

