scalar DateTime

enum ProductSource {
    Manual
    Steam
    Wildberries
}

type Price {
    currency: String!
    value: Float!
}

type Booking {
    nickname: String!
    date: String!
}

type Wish {
    id: ID!
    name: String!
    description: String
    link: String
    img: String
    rate: Int!
    type: ProductSource!
    price: Price
    creator: User!
    wishlists: [Wishlist!]!
    createdAt: DateTime!
    updatedAt: DateTime!
}

type Wishlist {
    id: ID!
    name: String!
    description: String
    creator: User!
    wishes: [Wish!]!
    createdAt: DateTime!
    updatedAt: DateTime!
}

type Product {
    name: String!
    description: String
    link: String
    img: String
    type: ProductSource!
    price: Price
}

type User {
    id: ID!
    telegramId: String!
    username: String!
    firstName: String!
    lastName: String
    photoUrl: String
    wishlists: [Wishlist!]!
    wishes: [Wish!]!
}

input AuthPayload {
    id: Int!
    first_name: String!
    last_name: String
    username: String!
    photo_url: String
    auth_date: Int!
    hash: String!
}

input PriceInput {
    currency: String!
    value: Float!
}

input CreateWishInput {
    name: String!
    description: String
    link: String
    img: String
    rate: Int
    price: PriceInput
    wishlistIds: [ID!]!
}

input UpdateWishInput {
    name: String
    description: String
    img: String
    rate: Int
    price: PriceInput
    wishlistIds: [ID!]
}

input CreateWishlistInput {
    name: String!
    description: String
    wishIds: [ID!]
}

input UpdateWishlistInput {
    name: String
    description: String
    wishIds: [ID!]
}

type Query {
    me: User!
    user(id: ID!): User
    productByUrl(url: String!): Product!
    wish(id: ID!): Wish!
    wishes: [Wish!]!
    wishlist(id: ID!): Wishlist!
    wishlists: [Wishlist!]!
}

type Mutation {
    login(authPayload: AuthPayload!): User
    logout: Boolean!
    createWish(input: CreateWishInput!): Wish!
    updateWish(id: ID!, input: UpdateWishInput!): Wish!
    deleteWish(id: ID!): Boolean!
    createWishlist(input: CreateWishlistInput!): Wishlist!
    updateWishlist(id: ID!, input: UpdateWishlistInput!): Wishlist!
}
