# === GraphiQL & GraphQL ===
spring.graphql.graphiql.enabled=true
# === DataSource / JPA ===
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# === Security ===
security.jwt.ttl=P1D
# === Logging ===
logging.level.root=WARN
logging.level.org.springframework.web=DEBUG
logging.level.com.whereisagift=DEBUG
# === GlitchTip ===
sentry.send-default-pii=true
sentry.traces-sample-rate=0.1
sentry.logging.minimum-event-level=error
sentry.logging.minimum-breadcrumb-level=debug
# === ===
spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true
# === I18n ===
spring.messages.basename=lang/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
# === Runtime ===
